// <auto-generated />
using System;
using AltarWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltarWeb.Migrations
{
    [DbContext(typeof(AltarDbContext))]
    [Migration("20260702195258_AgregarHaceCatrinaAEquipo")]
    partial class AgregarHaceCatrinaAEquipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AltarWeb.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodoRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorAuth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("AltarWeb.Models.AlumnoEquipo", b =>
                {
                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsCreador")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.HasKey("AlumnoId", "EquipoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("AlumnoEquipos");
                });

            modelBuilder.Entity("AltarWeb.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CreadoPorAlumnoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeriodoAcademico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SnapshotNombreCreador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorAlumnoId");

                    b.HasIndex("NombreEquipo", "PeriodoAcademico")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusTematicos")
                        .HasColumnType("int");

                    b.Property<bool>("ChkAgua")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkCalaveritas")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkFlor")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkFoto")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkIncienso")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkObjetos")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkPan")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkPapel")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkSal")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkVelas")
                        .HasColumnType("bit");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JuezId")
                        .HasColumnType("int");

                    b.Property<string>("Niveles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDifunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreJuez")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NotaEstetica")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaPersonalizacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaPersonalizacionFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaTradicion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaTradicionFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotNombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAltar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("JuezId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("AltarWeb.Models.Integrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.ToTable("Integrantes");
                });

            modelBuilder.Entity("AltarWeb.Models.Juez", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jueces");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.CatalogoCarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CatalogoCarreras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Lic. en Sistemas Computacionales",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Bioingeniero",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Ing. Aeroespacial",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Ing. Civil",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Ing. en Computación",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Ing. en Electrónica",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Ing. Eléctrico",
                            Orden = 7
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Ing. en Energías Renovables",
                            Orden = 8
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "Ing. Industrial",
                            Orden = 9
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Nombre = "Ing. Mecánico",
                            Orden = 10
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Nombre = "Ing. en Mecatrónica",
                            Orden = 11
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Nombre = "Ing. en Semiconductores y Microelectrónica",
                            Orden = 12
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Nombre = "Ing. de Datos e Inteligencia Artificial",
                            Orden = 13
                        });
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.CatalogoGenero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CatalogoGeneros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Masculino",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Femenino",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "No binario",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Prefiero no especificar",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Otro",
                            Orden = 5
                        });
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.ConfiguracionPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusPorElementoTematizado")
                        .HasColumnType("decimal(5,4)");

                    b.Property<bool>("ExigirMinimoUnAnioFallecimiento")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaLimiteInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteRequisitos")
                        .HasColumnType("datetime2");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PesoDistribucionNiveles")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PesoElementoDecorativo")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PesoElementoRitual")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PesoEsenciaPersonalidad")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PesoNarrador")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PesoObjetivoCultural")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PesoValoracionGeneral")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("RecorridoPdf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorSatisfaccionMuySatisfactorio")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("ValorSatisfaccionNoPresente")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("ValorSatisfaccionPoco")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("ValorSatisfaccionSatisfactorio")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("Periodo")
                        .IsUnique();

                    b.ToTable("ConfiguracionesPeriodo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusPorElementoTematizado = 0.25m,
                            ExigirMinimoUnAnioFallecimiento = true,
                            Periodo = "2026-1",
                            PesoDistribucionNiveles = 0.10m,
                            PesoElementoDecorativo = 0.5m,
                            PesoElementoRitual = 1.0m,
                            PesoEsenciaPersonalidad = 0.30m,
                            PesoNarrador = 0.10m,
                            PesoObjetivoCultural = 0.30m,
                            PesoValoracionGeneral = 0.20m,
                            ValorSatisfaccionMuySatisfactorio = 1.0m,
                            ValorSatisfaccionNoPresente = 0.0m,
                            ValorSatisfaccionPoco = 0.5m,
                            ValorSatisfaccionSatisfactorio = 0.75m
                        });
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Difunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaDefuncion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemblanzaHobbiesTematica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAltar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("Difuntos", (string)null);
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Elemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Colocacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NivelSugerido3")
                        .HasColumnType("int");

                    b.Property<int?>("NivelSugerido7")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Significado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Elementos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "En un vaso de cristal.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 2,
                            Nombre = "El Agua",
                            Orden = 1,
                            Significado = "Fuente de la vida; mitiga la sed de las almas tras su viaje y simboliza la pureza del alma."
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Jarra o jofaina acompañada de jabón pequeño y toalla/pañuelo limpio, para que el difunto se refresque al llegar.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 2,
                            Nombre = "El Aguamanil y kit de aseo",
                            Orden = 2,
                            Significado = "Símbolo de purificación y hospitalidad."
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "En un plato pequeño, a veces formando una cruz hacia los cuatro puntos cardinales; suele acompañar al vaso de agua.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 2,
                            Nombre = "La Sal",
                            Orden = 3,
                            Significado = "Principal elemento de purificación; limpia y protege el alma para que no se corrompa en su viaje; equilibrio espiritual."
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Formando una cruz (cuatro puntos cardinales) y alrededor del camino y del altar; veladoras de vaso o cirios según la región.",
                            NivelSugerido3 = 2,
                            NivelSugerido7 = 4,
                            Nombre = "Velas y Veladoras",
                            Orden = 4,
                            Significado = "Fuego, luz, fe y esperanza; guían a las almas hacia el altar y de regreso."
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Tradicionalmente en el penúltimo nivel o cerca de las imágenes.",
                            NivelSugerido3 = 3,
                            NivelSugerido7 = 6,
                            Nombre = "Incienso y Copal",
                            Orden = 5,
                            Significado = "El humo limpia las malas energías, purifica el ambiente y guía olfativamente a las almas. El copal es prehispánico (purificación y conexión espiritual); el incienso se asocia a la oración."
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Senderos de pétalos hacia el altar, en jarrones/coronas y en arcos de bienvenida.",
                            NivelSugerido3 = 2,
                            NivelSugerido7 = 3,
                            Nombre = "Flor de Cempasúchil",
                            Orden = 6,
                            Significado = "Elemento principal; su color naranja representa el sol y su aroma guía a las almas a casa."
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "En la parte superior del altar para que el difunto reconozca su hogar.",
                            NivelSugerido3 = 3,
                            NivelSugerido7 = 7,
                            Nombre = "El Retrato del Difunto",
                            Orden = 7,
                            Significado = "Corazón de la ofrenda; sugiere el ánima que visitará a la familia."
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Decorativas sobre el altar, coloridas con glaseado real.",
                            NivelSugerido3 = 2,
                            NivelSugerido7 = 3,
                            Nombre = "Calaveras de Azúcar",
                            Orden = 8,
                            Significado = "Representan la muerte, la vida efímera y el alma del difunto; evolución del tzompantli. Suelen llevar el nombre del ser querido en la frente."
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Tequila, mezcal, cerveza o bebidas artesanales que disfrutaba en vida.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 2,
                            Nombre = "El Licor (\"el trago\")",
                            Orden = 9,
                            Significado = "Para que el difunto recuerde los momentos de alegría que vivió."
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Cruz grande de ceniza en el altar.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 2,
                            Nombre = "Cruz de Ceniza",
                            Orden = 10,
                            Significado = "Expiación y purificación; ayuda al alma a expiar culpas y salir del purgatorio para visitar a los suyos."
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Colgado sobre el altar y el espacio.",
                            NivelSugerido3 = 3,
                            NivelSugerido7 = 6,
                            Nombre = "Papel Picado",
                            Orden = 11,
                            Significado = "Elemento aire y fragilidad de la vida; al moverse con la brisa indica que las almas han llegado. Cada color tiene significado (naranja=sol/vida; morado=luto; blanco=pureza/niños; negro=inframundo; rosa=celebración; rojo=vida/sacrificio; azul=fallecidos por agua)."
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Puede ser cualquier árbol/rama.",
                            NivelSugerido3 = 2,
                            NivelSugerido7 = 3,
                            Nombre = "La Vara (árbol)",
                            Orden = 12,
                            Significado = "Herramienta espiritual para que el difunto se defienda de malos espíritus y supere obstáculos en su viaje; considerado elemento de vida."
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Como base/mantel; puede adornarse con flores.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 1,
                            Nombre = "El Petate",
                            Orden = 13,
                            Significado = "Cama tejida de palma para que las ánimas descansen tras su travesía; también funciona como mantel/base de la ofrenda y une el mundo terrenal con el espiritual."
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Prendas, objetos de uso cotidiano, artículos de pasatiempos y, para niños, juguetes.",
                            NivelSugerido3 = 2,
                            NivelSugerido7 = 3,
                            Nombre = "Objetos Personales",
                            Orden = 14,
                            Significado = "Conectan el alma con su identidad y lo que apreciaba en vida."
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Sobre la ofrenda.",
                            NivelSugerido3 = 2,
                            NivelSugerido7 = 4,
                            Nombre = "Pan de Muerto",
                            Orden = 15,
                            Significado = "El más emblemático; ciclo de vida y muerte, fraternidad y ofrecimiento de alimento. La forma circular=eternidad; la esfera superior=cráneo/alma; las canillas=huesos y lágrimas (puntos cardinales); azúcar/ajonjolí=dulzura de la vida."
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Sobre el petate/mantel.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 1,
                            Nombre = "Comida y Bebida",
                            Orden = 16,
                            Significado = "Platillos, bebidas y dulces favoritos del difunto para deleitarlo en su visita."
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "En los niveles superiores junto a las imágenes.",
                            NivelSugerido3 = 3,
                            NivelSugerido7 = 7,
                            Nombre = "Objetos Religiosos o Místicos",
                            Orden = 17,
                            Significado = "Si el difunto era devoto, se incluyen rosarios, crucifijos, figuras de santos o amuletos."
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "En el nivel superior, mirando al frente, junto a las fotografías; de madera, resina o metal.",
                            NivelSugerido3 = 3,
                            NivelSugerido7 = 7,
                            Nombre = "Crucifijo",
                            Orden = 18,
                            Significado = "Simboliza la fe y sirve para que el ánima expíe sus culpas pendientes."
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "En la cúspide/último nivel o al frente del altar; tradicionalmente de carrizo, palma o madera flexible, con cruz de palma al centro, adornado con cempasúchil (frutas opcionales).",
                            NivelSugerido3 = 3,
                            NivelSugerido7 = 7,
                            Nombre = "El Arco",
                            Orden = 19,
                            Significado = "Puerta/umbral que une el mundo de los vivos con el más allá y da la bienvenida a las almas."
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Categoria = "RitualObligatorio",
                            Colocacion = "Camino de pétalos de cempasúchil (opcional sobre base de aserrín) desde el último escalón hasta el arco de bienvenida, acompañado de veladoras encendidas a los lados.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 1,
                            Nombre = "El Camino",
                            Orden = 20,
                            Significado = "Sendero que guía a las almas desde el más allá hasta el altar y de regreso."
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Categoria = "Decorativo",
                            Colocacion = "Al final, como parte de la decoración general.",
                            NivelSugerido3 = 1,
                            NivelSugerido7 = 1,
                            Nombre = "Vasijas de Metal y de Barro",
                            Orden = 21,
                            Significado = "Elementos de decoración del altar."
                        });
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.ElementoEvaluado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElementoId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<int?>("NivelAsignado")
                        .HasColumnType("int");

                    b.Property<string>("Satisfaccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Tematizado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ElementoId");

                    b.HasIndex("EvaluacionId", "ElementoId")
                        .IsUnique();

                    b.ToTable("ElementosEvaluados", (string)null);
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreadoPorRegistranteId")
                        .HasColumnType("int");

                    b.Property<bool>("HaceCatrina")
                        .HasColumnType("bit");

                    b.Property<int?>("MaestroEncargadoId")
                        .HasColumnType("int");

                    b.Property<string>("MaestroEncargadoIdentificadorPendiente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreAltar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UbicacionAltar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("CreadoPorRegistranteId");

                    b.HasIndex("MaestroEncargadoId");

                    b.HasIndex("Nombre", "Periodo")
                        .IsUnique();

                    b.ToTable("EquiposConcurso", (string)null);
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DistribucionNiveles")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<decimal>("EsenciaPersonalidad")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("EsenciaPersonalidadFinal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IncluyeCatrina")
                        .HasColumnType("bit");

                    b.Property<int?>("JuezId")
                        .HasColumnType("int");

                    b.Property<int?>("Lugar")
                        .HasColumnType("int");

                    b.Property<decimal>("Narrador")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Niveles")
                        .HasColumnType("int");

                    b.Property<decimal?>("NotaFinal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ObjetivoCultural")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PuntajeElementos")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly?>("SnapshotDifuntoFechaDefuncion")
                        .HasColumnType("date");

                    b.Property<string>("SnapshotDifuntoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotNombreAltar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotNombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TematicaHobbies")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ValoracionGeneral")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.HasIndex("JuezId");

                    b.ToTable("EvaluacionesConcurso", (string)null);
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.EvaluacionCatrina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Collar")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Guantes")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("LugarCatrina")
                        .HasColumnType("int");

                    b.Property<decimal>("Maquillaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NotaCatrina")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SombreroTocado")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Vestimenta")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Zapatos")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId")
                        .IsUnique();

                    b.ToTable("EvaluacionesCatrina", (string)null);
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.EvaluacionIntegrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistranteId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("RegistranteId");

                    b.ToTable("EvaluacionIntegrantes", (string)null);
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Registrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("AutodescripcionCultural")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CatalogoCarreraId")
                        .HasColumnType("int");

                    b.Property<int?>("CatalogoGeneroId")
                        .HasColumnType("int");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorAuth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoCarreraId");

                    b.HasIndex("CatalogoGeneroId");

                    b.HasIndex("CorreoInstitucional")
                        .IsUnique();

                    b.HasIndex("Identificador")
                        .IsUnique();

                    b.ToTable("Registrantes", (string)null);
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.RegistranteEquipo", b =>
                {
                    b.Property<int>("RegistranteId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RegistranteId", "EquipoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("RegistranteEquipos", (string)null);
                });

            modelBuilder.Entity("AltarWeb.Models.AlumnoEquipo", b =>
                {
                    b.HasOne("AltarWeb.Models.Alumno", "Alumno")
                        .WithMany("Equipos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AltarWeb.Models.Equipo", "Equipo")
                        .WithMany("Integrantes")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("AltarWeb.Models.Equipo", b =>
                {
                    b.HasOne("AltarWeb.Models.Alumno", "CreadoPorAlumno")
                        .WithMany()
                        .HasForeignKey("CreadoPorAlumnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPorAlumno");
                });

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.HasOne("AltarWeb.Models.Equipo", "Equipo")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AltarWeb.Models.Juez", "Juez")
                        .WithMany()
                        .HasForeignKey("JuezId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");

                    b.Navigation("Juez");
                });

            modelBuilder.Entity("AltarWeb.Models.Integrante", b =>
                {
                    b.HasOne("AltarWeb.Models.Evaluacion", "Evaluacion")
                        .WithMany("Integrantes")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Difunto", b =>
                {
                    b.HasOne("AltarWeb.Models.Registro.Equipo", "Equipo")
                        .WithOne("Difunto")
                        .HasForeignKey("AltarWeb.Models.Registro.Difunto", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.ElementoEvaluado", b =>
                {
                    b.HasOne("AltarWeb.Models.Registro.Elemento", "Elemento")
                        .WithMany()
                        .HasForeignKey("ElementoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AltarWeb.Models.Registro.Evaluacion", "Evaluacion")
                        .WithMany("ElementosEvaluados")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elemento");

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Equipo", b =>
                {
                    b.HasOne("AltarWeb.Models.Registro.CatalogoCarrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AltarWeb.Models.Registro.Registrante", "CreadoPorRegistrante")
                        .WithMany()
                        .HasForeignKey("CreadoPorRegistranteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AltarWeb.Models.Registro.Registrante", "MaestroEncargado")
                        .WithMany()
                        .HasForeignKey("MaestroEncargadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carrera");

                    b.Navigation("CreadoPorRegistrante");

                    b.Navigation("MaestroEncargado");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Evaluacion", b =>
                {
                    b.HasOne("AltarWeb.Models.Registro.Equipo", "Equipo")
                        .WithOne("Evaluacion")
                        .HasForeignKey("AltarWeb.Models.Registro.Evaluacion", "EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AltarWeb.Models.Juez", "Juez")
                        .WithMany()
                        .HasForeignKey("JuezId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");

                    b.Navigation("Juez");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.EvaluacionCatrina", b =>
                {
                    b.HasOne("AltarWeb.Models.Registro.Evaluacion", "Evaluacion")
                        .WithOne("EvaluacionCatrina")
                        .HasForeignKey("AltarWeb.Models.Registro.EvaluacionCatrina", "EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.EvaluacionIntegrante", b =>
                {
                    b.HasOne("AltarWeb.Models.Registro.Evaluacion", "Evaluacion")
                        .WithMany("Integrantes")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AltarWeb.Models.Registro.Registrante", "Registrante")
                        .WithMany()
                        .HasForeignKey("RegistranteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Evaluacion");

                    b.Navigation("Registrante");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Registrante", b =>
                {
                    b.HasOne("AltarWeb.Models.Registro.CatalogoCarrera", "CatalogoCarrera")
                        .WithMany()
                        .HasForeignKey("CatalogoCarreraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AltarWeb.Models.Registro.CatalogoGenero", "CatalogoGenero")
                        .WithMany()
                        .HasForeignKey("CatalogoGeneroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CatalogoCarrera");

                    b.Navigation("CatalogoGenero");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.RegistranteEquipo", b =>
                {
                    b.HasOne("AltarWeb.Models.Registro.Equipo", "Equipo")
                        .WithMany("Integrantes")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AltarWeb.Models.Registro.Registrante", "Registrante")
                        .WithMany("Equipos")
                        .HasForeignKey("RegistranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Registrante");
                });

            modelBuilder.Entity("AltarWeb.Models.Alumno", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("AltarWeb.Models.Equipo", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Equipo", b =>
                {
                    b.Navigation("Difunto");

                    b.Navigation("Evaluacion");

                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Evaluacion", b =>
                {
                    b.Navigation("ElementosEvaluados");

                    b.Navigation("EvaluacionCatrina");

                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.Registrante", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
