// <auto-generated />
using System;
using AltarWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltarWeb.Migrations
{
    [DbContext(typeof(AltarDbContext))]
    [Migration("20260429201444_AddIntegranteSoftDelete")]
    partial class AddIntegranteSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusTematicos")
                        .HasColumnType("int");

                    b.Property<bool>("ChkAgua")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkCalaveritas")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkFlor")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkFoto")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkIncienso")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkObjetos")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkPan")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkPapel")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkSal")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkVelas")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JuezId")
                        .HasColumnType("int");

                    b.Property<string>("Niveles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDifunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreJuez")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NotaEstetica")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaPersonalizacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaTradicion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAltar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JuezId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("AltarWeb.Models.Integrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.ToTable("Integrantes");
                });

            modelBuilder.Entity("AltarWeb.Models.Juez", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jueces");
                });

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.HasOne("AltarWeb.Models.Juez", "Juez")
                        .WithMany()
                        .HasForeignKey("JuezId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Juez");
                });

            modelBuilder.Entity("AltarWeb.Models.Integrante", b =>
                {
                    b.HasOne("AltarWeb.Models.Evaluacion", "Evaluacion")
                        .WithMany("Integrantes")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.Navigation("Integrantes");
                });
#pragma warning restore 612, 618
        }
    }
}
