// <auto-generated />
using System;
using AltarWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltarWeb.Migrations
{
    [DbContext(typeof(AltarDbContext))]
    [Migration("20260701190749_AddCatalogosGeneroYCarrera")]
    partial class AddCatalogosGeneroYCarrera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AltarWeb.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodoRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorAuth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("AltarWeb.Models.AlumnoEquipo", b =>
                {
                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsCreador")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.HasKey("AlumnoId", "EquipoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("AlumnoEquipos");
                });

            modelBuilder.Entity("AltarWeb.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CreadoPorAlumnoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeriodoAcademico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SnapshotNombreCreador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorAlumnoId");

                    b.HasIndex("NombreEquipo", "PeriodoAcademico")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusTematicos")
                        .HasColumnType("int");

                    b.Property<bool>("ChkAgua")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkCalaveritas")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkFlor")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkFoto")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkIncienso")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkObjetos")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkPan")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkPapel")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkSal")
                        .HasColumnType("bit");

                    b.Property<bool>("ChkVelas")
                        .HasColumnType("bit");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JuezId")
                        .HasColumnType("int");

                    b.Property<string>("Niveles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDifunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreJuez")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NotaEstetica")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaPersonalizacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaPersonalizacionFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaTradicion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaTradicionFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotNombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAltar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("JuezId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("AltarWeb.Models.Integrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.ToTable("Integrantes");
                });

            modelBuilder.Entity("AltarWeb.Models.Juez", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jueces");
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.CatalogoCarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CatalogoCarreras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Lic. en Sistemas Computacionales",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Bioingeniero",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Ing. Aeroespacial",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Ing. Civil",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Ing. en Computación",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Ing. en Electrónica",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Ing. Eléctrico",
                            Orden = 7
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Ing. en Energías Renovables",
                            Orden = 8
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "Ing. Industrial",
                            Orden = 9
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Nombre = "Ing. Mecánico",
                            Orden = 10
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Nombre = "Ing. en Mecatrónica",
                            Orden = 11
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Nombre = "Ing. en Semiconductores y Microelectrónica",
                            Orden = 12
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Nombre = "Ing. de Datos e Inteligencia Artificial",
                            Orden = 13
                        });
                });

            modelBuilder.Entity("AltarWeb.Models.Registro.CatalogoGenero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CatalogoGeneros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Masculino",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Femenino",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "No binario",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Prefiero no especificar",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Otro",
                            Orden = 5
                        });
                });

            modelBuilder.Entity("AltarWeb.Models.AlumnoEquipo", b =>
                {
                    b.HasOne("AltarWeb.Models.Alumno", "Alumno")
                        .WithMany("Equipos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AltarWeb.Models.Equipo", "Equipo")
                        .WithMany("Integrantes")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("AltarWeb.Models.Equipo", b =>
                {
                    b.HasOne("AltarWeb.Models.Alumno", "CreadoPorAlumno")
                        .WithMany()
                        .HasForeignKey("CreadoPorAlumnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPorAlumno");
                });

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.HasOne("AltarWeb.Models.Equipo", "Equipo")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AltarWeb.Models.Juez", "Juez")
                        .WithMany()
                        .HasForeignKey("JuezId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");

                    b.Navigation("Juez");
                });

            modelBuilder.Entity("AltarWeb.Models.Integrante", b =>
                {
                    b.HasOne("AltarWeb.Models.Evaluacion", "Evaluacion")
                        .WithMany("Integrantes")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("AltarWeb.Models.Alumno", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("AltarWeb.Models.Equipo", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("AltarWeb.Models.Evaluacion", b =>
                {
                    b.Navigation("Integrantes");
                });
#pragma warning restore 612, 618
        }
    }
}
